import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BookOpen, Leaf, Zap, Plane, Trash2, FileCheck, HelpCircle } from "lucide-react";

const resources = [
  { icon: Leaf, title: "What is Carbon Footprint?", content: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. For CA firms and ICAI offices, this includes electricity, travel, paper, waste, and other operational activities." },
  { icon: BookOpen, title: "Understanding Scope 1, 2 and 3", content: "Scope 1 covers direct emissions from owned sources (DG sets, vehicles). Scope 2 covers indirect emissions from purchased electricity. Scope 3 covers all other indirect emissions (travel, paper, waste, hotel stays)." },
  { icon: Zap, title: "How to Reduce Electricity Emissions", content: "Switch to LED lighting, use energy-efficient appliances, install solar panels, optimize AC usage, and consider green electricity tariffs from your utility provider." },
  { icon: Plane, title: "How to Reduce Travel Emissions", content: "Prefer virtual meetings, use rail for short distances, combine trips, choose economy class for flights, and promote public transport for office commutes." },
  { icon: Trash2, title: "Waste Management Tips", content: "Implement waste segregation, partner with recycling vendors, reduce single-use items, compost organic waste, and properly dispose of e-waste through authorized recyclers." },
  { icon: FileCheck, title: "Reporting Guidance", content: "Collect activity data for the reporting period, use current emission factors, upload supporting documents, review calculations, generate reports, and submit through the portal before deadlines." },
  { icon: HelpCircle, title: "Frequently Asked Questions", content: "Q: Which emission factors should I use? A: Use the latest active factors from the admin-managed factor library. Q: How often should I report? A: Annually per ICAI reporting calendar. Q: Can I save drafts? A: Yes, calculations can be saved as drafts and resumed later." },
];

export default function ResourcesPage() {
  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold">Educational Resources</h1>
        <p className="text-muted-foreground">Guidance on carbon footprint and sustainability reporting</p>
      </div>
      <div className="space-y-4">
        {resources.map((r) => (
          <Card key={r.title}>
            <CardHeader className="pb-2">
              <div className="flex items-center gap-2">
                <r.icon className="h-5 w-5 text-teal-600" />
                <CardTitle className="text-base">{r.title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent><p className="text-sm text-muted-foreground leading-relaxed">{r.content}</p></CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
