"use client";

import type { GeneratedReport } from "@/lib/types";
import { REPORT_DISCLAIMER } from "@/lib/reportUtils";
import { CarbonLogo } from "@/components/common/CarbonLogo";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export function ReportPreview({ report }: { report: GeneratedReport }) {
  return (
    <Card className="max-w-3xl mx-auto border-2">
      <CardContent className="p-8 space-y-6">
        <div className="flex items-center justify-between">
          <CarbonLogo />
          <div className="text-right text-sm text-muted-foreground">
            <p>ICAI Branding Placeholder</p>
            <p>Institute of Chartered Accountants of India</p>
          </div>
        </div>
        <Separator />
        <div className="text-center">
          <h2 className="text-xl font-bold">GHG Emission Report</h2>
          <p className="text-muted-foreground">{report.reportName}</p>
        </div>
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div><span className="text-muted-foreground">Entity:</span> <strong>{report.entityName}</strong></div>
          <div><span className="text-muted-foreground">Type:</span> <strong>{report.entityType}</strong></div>
          <div><span className="text-muted-foreground">Region:</span> <strong>{report.regionName}</strong></div>
          <div><span className="text-muted-foreground">Period:</span> <strong>{report.reportingPeriod}</strong></div>
          <div><span className="text-muted-foreground">Generated By:</span> <strong>{report.generatedBy}</strong></div>
          <div><span className="text-muted-foreground">Date:</span> <strong>{new Date(report.generatedDate).toLocaleDateString()}</strong></div>
        </div>
        <div className="rounded-lg bg-teal-50 p-4 text-center">
          <p className="text-sm text-teal-700">Total CO2e Footprint</p>
          <p className="text-3xl font-bold text-teal-800">{report.totalCo2e.toLocaleString()} kg</p>
        </div>
        <div>
          <h3 className="font-semibold mb-2">Scope-wise Summary</h3>
          <div className="grid grid-cols-3 gap-2 text-sm">
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 1</p><p className="font-bold">{report.scope1Total.toFixed(0)} kg</p></div>
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 2</p><p className="font-bold">{report.scope2Total.toFixed(0)} kg</p></div>
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 3</p><p className="font-bold">{report.scope3Total.toFixed(0)} kg</p></div>
          </div>
        </div>
        {report.categoryBreakdown.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Category-wise Summary</h3>
            <table className="w-full text-sm">
              <thead><tr className="border-b"><th className="text-left py-1">Category</th><th className="text-right">CO2e (kg)</th><th className="text-right">Scope</th></tr></thead>
              <tbody>
                {report.categoryBreakdown.map((c, i) => (
                  <tr key={i} className="border-b"><td className="py-1">{c.category}</td><td className="text-right">{c.co2e.toFixed(2)}</td><td className="text-right">{c.scope}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        <div className="rounded-lg border-2 border-dashed h-32 flex items-center justify-center text-muted-foreground text-sm">
          Chart Placeholder — Category & Scope Visualizations
        </div>
        <div>
          <h3 className="font-semibold mb-1">Recommendations Summary</h3>
          <p className="text-sm text-muted-foreground">Review sustainability recommendations in the portal for emission reduction opportunities.</p>
        </div>
        <Separator />
        <p className="text-xs text-muted-foreground italic">{REPORT_DISCLAIMER}</p>
      </CardContent>
    </Card>
  );
}
