"use client";

import type { GeneratedReport } from "@/lib/types";
import { METHODOLOGY_NOTE, REPORT_DISCLAIMER } from "@/lib/reportUtils";
import { CarbonLogo } from "@/components/common/CarbonLogo";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Printer, Download } from "lucide-react";
import { useAppStore } from "@/store/useAppStore";
import { toast } from "sonner";

export function ReportPreview({
  report,
  showActions = true,
  embedded = false,
}: {
  report: GeneratedReport;
  showActions?: boolean;
  /** Full-width layout for modal preview */
  embedded?: boolean;
}) {
  const downloadReport = useAppStore((s) => s.downloadReport);
  const lineItems = report.lineItems ?? [];

  const handleDownload = () => {
    const ok = downloadReport(report.id);
    if (ok) {
      toast.success(
        report.format === "Excel"
          ? "Excel-compatible CSV downloaded"
          : "Print dialog opened — choose Save as PDF"
      );
    } else {
      toast.error("Failed to export report");
    }
  };

  return (
    <Card
      className={embedded ? "w-full border-0 shadow-none" : "max-w-3xl mx-auto border-2"}
      id={`report-preview-${report.id}`}
    >
      <CardContent className={embedded ? "p-2 sm:p-4 space-y-6" : "p-8 space-y-6"}>
        <div className="flex items-center justify-between gap-4">
          <CarbonLogo />
          <div className="text-right text-sm text-muted-foreground">
            <p>ICAI Branding Placeholder</p>
            <p>Institute of Chartered Accountants of India</p>
          </div>
        </div>
        <Separator />
        <div className="text-center">
          <h2 className="text-xl font-bold">ICAI Carbon Emission Calculator</h2>
          <p className="text-muted-foreground mt-1">GHG Emission Report</p>
          <p className="text-sm text-muted-foreground">{report.reportName}</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
          <div><span className="text-muted-foreground">Entity:</span> <strong>{report.entityName}</strong></div>
          <div><span className="text-muted-foreground">Type:</span> <strong>{report.entityType}</strong></div>
          <div><span className="text-muted-foreground">Region:</span> <strong>{report.regionName}</strong></div>
          <div><span className="text-muted-foreground">Period:</span> <strong>{report.reportingPeriod}</strong></div>
          <div><span className="text-muted-foreground">Generated By:</span> <strong>{report.generatedBy}</strong></div>
          <div><span className="text-muted-foreground">Email:</span> <strong>{report.generatedByEmail ?? "—"}</strong></div>
          <div><span className="text-muted-foreground">Report ID:</span> <strong>{report.id}</strong></div>
          <div><span className="text-muted-foreground">Date:</span> <strong>{new Date(report.generatedDate).toLocaleString()}</strong></div>
        </div>
        <div className="rounded-lg bg-primary/10 p-4 text-center">
          <p className="text-sm text-primary">Total CO₂e Footprint</p>
          <p className="text-3xl font-bold text-primary">{report.totalCo2e.toLocaleString()} kg</p>
        </div>
        <div>
          <h3 className="font-semibold mb-2">Scope-wise Summary</h3>
          <div className="grid grid-cols-3 gap-2 text-sm">
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 1</p><p className="font-bold">{report.scope1Total.toFixed(2)} kg</p></div>
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 2</p><p className="font-bold">{report.scope2Total.toFixed(2)} kg</p></div>
            <div className="rounded border p-2 text-center"><p className="text-muted-foreground">Scope 3</p><p className="font-bold">{report.scope3Total.toFixed(2)} kg</p></div>
          </div>
        </div>
        {report.categoryBreakdown.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Category-wise Breakdown</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead><tr className="border-b bg-slate-50"><th className="text-left py-2 px-1">Category</th><th className="text-right py-2 px-1">CO₂e (kg)</th><th className="text-right py-2 px-1">Scope</th></tr></thead>
                <tbody>
                  {report.categoryBreakdown.map((c, i) => (
                    <tr key={i} className="border-b"><td className="py-1.5 px-1">{c.category}</td><td className="text-right px-1">{c.co2e.toFixed(2)}</td><td className="text-right px-1">{c.scope}</td></tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
        {lineItems.length > 0 && (
          <div>
            <h3 className="font-semibold mb-2">Activity Line Items</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead><tr className="border-b bg-slate-50"><th className="text-left py-2 px-1">Category</th><th className="text-right py-2 px-1">Qty</th><th className="text-right py-2 px-1">Unit</th><th className="text-right py-2 px-1">Factor</th><th className="text-right py-2 px-1">CO₂e</th><th className="text-right py-2 px-1">Scope</th></tr></thead>
                <tbody>
                  {lineItems.map((li) => (
                    <tr key={li.id} className="border-b">
                      <td className="py-1.5 px-1">{li.categoryName}</td>
                      <td className="text-right px-1">{li.activityQuantity}</td>
                      <td className="text-right px-1">{li.unit}</td>
                      <td className="text-right px-1">{li.emissionFactor}</td>
                      <td className="text-right px-1">{li.co2e.toFixed(2)}</td>
                      <td className="text-right px-1">{li.scope}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
        <div>
          <h3 className="font-semibold mb-1">Recommendations Summary</h3>
          {report.recommendationsSummary?.length ? (
            <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
              {report.recommendationsSummary.map((r) => <li key={r}>{r}</li>)}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">Review sustainability recommendations in the portal for emission reduction opportunities.</p>
          )}
        </div>
        <Separator />
        <p className="text-xs text-muted-foreground"><strong>Methodology:</strong> {METHODOLOGY_NOTE}</p>
        <p className="text-xs text-muted-foreground italic"><strong>Disclaimer:</strong> {REPORT_DISCLAIMER}</p>
        {showActions && (
          <div className="flex flex-wrap gap-2 pt-2">
            <Button className="bg-primary hover:bg-primary/90" onClick={handleDownload}>
              <Download className="h-4 w-4 mr-1" />
              {report.format === "Excel" ? "Download CSV (Excel)" : "Print / Save as PDF"}
            </Button>
            <Button variant="outline" onClick={() => {
              const ok = downloadReport(report.id);
              if (ok) toast.info("Print dialog opened");
              else toast.error("Failed to open print dialog");
            }}>
              <Printer className="h-4 w-4 mr-1" /> Print Report
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
