import type { Calculation, GeneratedReport, ReportFormat } from "./types";
import { getCategoryBreakdown } from "./calculationEngine";

export function generateReportFromCalculation(
  calculation: Calculation,
  format: ReportFormat,
  generatedBy: string
): GeneratedReport {
  const id = `RPT-${Date.now().toString(36).toUpperCase()}`;
  return {
    id,
    reportName: `${calculation.entityName} - ${calculation.reportingPeriod} Emission Report`,
    entityId: calculation.entityId,
    entityName: calculation.entityName,
    entityType: calculation.entityType,
    regionId: calculation.regionId,
    regionName: calculation.regionName,
    reportingPeriod: calculation.reportingPeriod,
    generatedBy,
    generatedDate: new Date().toISOString(),
    format,
    status: "Generated",
    totalCo2e: calculation.totalCo2e,
    scope1Total: calculation.scope1Total,
    scope2Total: calculation.scope2Total,
    scope3Total: calculation.scope3Total,
    calculationId: calculation.id,
    categoryBreakdown: getCategoryBreakdown(calculation.lineItems),
  };
}

export function generateRegionalReport(
  regionName: string,
  regionId: string,
  reportingPeriod: string,
  totalCo2e: number,
  generatedBy: string
): GeneratedReport {
  return {
    id: `RPT-REG-${Date.now().toString(36).toUpperCase()}`,
    reportName: `${regionName} Regional Emission Report - ${reportingPeriod}`,
    entityId: regionId,
    entityName: regionName,
    entityType: "Regional Office",
    regionId,
    regionName,
    reportingPeriod,
    generatedBy,
    generatedDate: new Date().toISOString(),
    format: "PDF",
    status: "Generated",
    totalCo2e,
    scope1Total: totalCo2e * 0.35,
    scope2Total: totalCo2e * 0.25,
    scope3Total: totalCo2e * 0.4,
    categoryBreakdown: [],
  };
}

export const REPORT_DISCLAIMER =
  "This report is generated by the ICAI Carbon Emission Calculator demo portal. Data presented is based on user-submitted activity data and applicable emission factors. This is a Proof of Concept (PoC) and should not be used for statutory compliance without verification. ICAI reserves the right to update emission factors and methodologies.";
