import type { GeneratedReport } from "./types";
import { METHODOLOGY_NOTE, REPORT_DISCLAIMER, buildReportFileName } from "./reportUtils";

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCsv(value: string | number): string {
  const s = String(value ?? "");
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function exportReportAsExcelCsv(report: GeneratedReport): void {
  const rows: (string | number)[][] = [
    ["ICAI Carbon Emission Calculator — GHG Emission Report"],
    [],
    ["Report ID", report.id],
    ["Entity", report.entityName],
    ["Entity Type", report.entityType],
    ["Region", report.regionName],
    ["Reporting Period", report.reportingPeriod],
    ["Generated By", report.generatedBy],
    ["Generated Email", report.generatedByEmail ?? ""],
    ["Generated Date", new Date(report.generatedDate).toLocaleString()],
    [],
    ["Total CO2e (kg)", report.totalCo2e],
    ["Scope 1 (kg)", report.scope1Total],
    ["Scope 2 (kg)", report.scope2Total],
    ["Scope 3 (kg)", report.scope3Total],
    [],
    ["Category Breakdown"],
    ["Category", "CO2e (kg)", "Scope"],
    ...report.categoryBreakdown.map((c) => [c.category, c.co2e, c.scope]),
    [],
    ["Activity Line Items"],
    ["Category", "Activity Qty", "Unit", "Factor", "CO2e (kg)", "Scope"],
    ...(report.lineItems ?? []).map((li) => [
      li.categoryName,
      li.activityQuantity,
      li.unit,
      li.emissionFactor,
      li.co2e,
      li.scope,
    ]),
    [],
    ["Methodology", METHODOLOGY_NOTE],
    ["Disclaimer", REPORT_DISCLAIMER],
  ];

  if (report.recommendationsSummary?.length) {
    rows.push([], ["Recommendations"]);
    report.recommendationsSummary.forEach((r) => rows.push([r]));
  }

  const csv = "\uFEFF" + rows.map((row) => row.map(escapeCsv).join(",")).join("\r\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  triggerDownload(blob, buildReportFileName(report, "csv"));
}

function buildPrintableHtml(report: GeneratedReport): string {
  const lineItems = report.lineItems ?? [];
  const categories = report.categoryBreakdown;
  const recs = report.recommendationsSummary ?? [];

  const lineRows = lineItems
    .map(
      (li) =>
        `<tr><td>${li.categoryName}</td><td>${li.activityQuantity}</td><td>${li.unit}</td><td>${li.emissionFactor}</td><td align="right">${li.co2e.toFixed(2)}</td><td>${li.scope}</td></tr>`
    )
    .join("");

  const catRows = categories
    .map(
      (c) =>
        `<tr><td>${c.category}</td><td align="right">${c.co2e.toFixed(2)}</td><td>${c.scope}</td></tr>`
    )
    .join("");

  const recList = recs.length
    ? `<ul>${recs.map((r) => `<li>${r}</li>`).join("")}</ul>`
    : "<p>Review sustainability recommendations in the portal.</p>";

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${report.reportName}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; }
  h1 { color: #0d9488; margin-bottom: 4px; }
  h2 { color: #334155; border-bottom: 2px solid #0d9488; padding-bottom: 6px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { border: 1px solid #cbd5e1; padding: 8px; font-size: 13px; }
  th { background: #f0fdfa; text-align: left; }
  .total { background: #ccfbf1; padding: 16px; text-align: center; border-radius: 8px; margin: 16px 0; }
  .total strong { font-size: 28px; color: #0f766e; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 13px; }
  .note { font-size: 12px; color: #64748b; margin-top: 24px; font-style: italic; }
  @media print { body { margin: 20px; } }
</style></head><body>
  <h1>ICAI Carbon Emission Calculator</h1>
  <p style="color:#64748b">GHG Emission Report — ${report.reportName}</p>
  <div class="meta">
    <div><strong>Entity:</strong> ${report.entityName}</div>
    <div><strong>Type:</strong> ${report.entityType}</div>
    <div><strong>Region:</strong> ${report.regionName}</div>
    <div><strong>Period:</strong> ${report.reportingPeriod}</div>
    <div><strong>Generated By:</strong> ${report.generatedBy}</div>
    <div><strong>Date:</strong> ${new Date(report.generatedDate).toLocaleString()}</div>
  </div>
  <div class="total"><div>Total CO₂e Footprint</div><strong>${report.totalCo2e.toLocaleString()} kg</strong></div>
  <h2>Scope-wise Summary</h2>
  <table><tr><th>Scope 1</th><th>Scope 2</th><th>Scope 3</th></tr>
  <tr><td align="center">${report.scope1Total.toFixed(2)} kg</td><td align="center">${report.scope2Total.toFixed(2)} kg</td><td align="center">${report.scope3Total.toFixed(2)} kg</td></tr></table>
  ${categories.length ? `<h2>Category-wise Breakdown</h2><table><tr><th>Category</th><th>CO₂e (kg)</th><th>Scope</th></tr>${catRows}</table>` : ""}
  ${lineItems.length ? `<h2>Activity Line Items</h2><table><tr><th>Category</th><th>Qty</th><th>Unit</th><th>Factor</th><th>CO₂e</th><th>Scope</th></tr>${lineRows}</table>` : ""}
  <h2>Recommendations</h2>${recList}
  <p class="note"><strong>Methodology:</strong> ${METHODOLOGY_NOTE}</p>
  <p class="note"><strong>Disclaimer:</strong> ${REPORT_DISCLAIMER}</p>
</body></html>`;
}

export function exportReportAsPdf(report: GeneratedReport): void {
  const html = buildPrintableHtml(report);
  const printWindow = window.open("", "_blank", "width=900,height=700");
  if (!printWindow) {
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    triggerDownload(blob, buildReportFileName(report, "html"));
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 400);
}

export function downloadReportFile(report: GeneratedReport): void {
  if (report.format === "Excel") {
    exportReportAsExcelCsv(report);
  } else {
    exportReportAsPdf(report);
  }
}
